// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbdb.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_0664d70518e46d1c, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Log struct {
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_0664d70518e46d1c, []int{1}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Incompat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Incompat) Reset()         { *m = Incompat{} }
func (m *Incompat) String() string { return proto.CompactTextString(m) }
func (*Incompat) ProtoMessage()    {}
func (*Incompat) Descriptor() ([]byte, []int) {
	return fileDescriptor_0664d70518e46d1c, []int{2}
}

func (m *Incompat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Incompat.Unmarshal(m, b)
}
func (m *Incompat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Incompat.Marshal(b, m, deterministic)
}
func (m *Incompat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Incompat.Merge(m, src)
}
func (m *Incompat) XXX_Size() int {
	return xxx_messageInfo_Incompat.Size(m)
}
func (m *Incompat) XXX_DiscardUnknown() {
	xxx_messageInfo_Incompat.DiscardUnknown(m)
}

var xxx_messageInfo_Incompat proto.InternalMessageInfo

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Log)(nil), "Log")
	proto.RegisterType((*Incompat)(nil), "Incompat")
}

func init() { proto.RegisterFile("pbdb.proto", fileDescriptor_0664d70518e46d1c) }

var fileDescriptor_0664d70518e46d1c = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x48, 0x4a, 0x49,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe2, 0x62, 0x09, 0x2d, 0x4e, 0x2d, 0x12, 0x92,
	0xe2, 0xe2, 0x28, 0x2d, 0x4e, 0x2d, 0xca, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x82, 0xf3, 0x95, 0xe4, 0xb9, 0x98, 0x7d, 0xf2, 0xd3, 0x85, 0x24, 0xb8, 0xd8, 0x73, 0x53,
	0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x25, 0x98, 0xc0, 0x2a, 0x60, 0x5c, 0x25, 0x2e, 0x2e, 0x0e, 0xcf,
	0xbc, 0xe4, 0xfc, 0xdc, 0x82, 0xc4, 0x12, 0x27, 0x8e, 0x28, 0x36, 0xb0, 0xc9, 0xc5, 0x49, 0x10,
	0xda, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x81, 0x0b, 0x6e, 0x6f, 0x00, 0x00, 0x00,
}
